"""add_stopped_status_to_sync_log

Revision ID: 10e924db684e
Revises: c7e2c6edebf5
Create Date: 2026-03-08 17:23:34.489271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e924db684e'
down_revision = 'c7e2c6edebf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='success, failed, in_progress, stopped',
               existing_comment='success, failed, in_progress',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='success, failed, in_progress',
               existing_comment='success, failed, in_progress, stopped',
               existing_nullable=False)

    # ### end Alembic commands ###
