"""add_sync_type_to_sync_logs

Revision ID: c7e2c6edebf5
Revises: 727d8085d452
Create Date: 2026-03-08 15:30:54.325305

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7e2c6edebf5"
down_revision = "727d8085d452"
branch_labels = None
depends_on = None


def upgrade():
    # Add column as nullable first, backfill, then set NOT NULL
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sync_type",
                sa.String(length=20),
                nullable=True,
                comment="full or changes",
            )
        )

    # Backfill existing rows
    op.execute("UPDATE sync_logs SET sync_type = 'full' WHERE sync_type IS NULL")

    # Now set NOT NULL
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "sync_type",
            existing_type=sa.String(length=20),
            nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            comment="success, failed, in_progress",
            existing_comment="success, failed",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            comment="success, failed",
            existing_comment="success, failed, in_progress",
            existing_nullable=False,
        )
        batch_op.drop_column("sync_type")

    # ### end Alembic commands ###
